Fixed bugs

diff --git a/playbooks/roles/assets_manager/templates/startup.sh.j2 b/playbooks/roles/assets_manager/templates/startup.sh.j2
--- a/playbooks/roles/assets_manager/templates/startup.sh.j2
+++ b/playbooks/roles/assets_manager/templates/startup.sh.j2
@@ -1,5 +1,45 @@
-
 #!/bin/bash
+#
+set -x
 
-JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
-$JAVA_HOME/bin/java -Xmx1g -jar {{app_name}}-{{app_version}}.jar
+# Set the defaullt JAVA_HOME for the OS family
+OS_FAMILY="$(uname -s)"
+case "${OS_FAMILY}" in
+    Linux*)
+        DEFAULT_JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))"
+        ;;
+    Darwin*)
+        DEFAULT_JAVA_HOME=$(/usr/libexec/java_home)
+        ;;
+    CYGWIN*)
+        DEFAULT_JAVA_HOME=""
+        ;;
+    *)
+        DEFAULT_JAVA_HOME=""
+        ;;
+esac
+
+# Use the default JAVA_HOME if it is not set
+JAVA_HOME=${JAVA_HOME:-${DEFAULT_JAVA_HOME}}
+JAVA_OPTS="-Xmx1g"
+
+JAVA_APM=""
+
+# Use Elastic APM agent if exists
+if [ -f "/usr/share/apm-agent/java/elastic-apm-agent-1.10.0.jar" ]; then
+JAVA_APM="-javaagent:/usr/share/apm-agent/java/elastic-apm-agent-1.10.0.jar \
+ -Delastic.apm.service_name=asset-manager \
+ -Delastic.apm.server_urls={{ apm_server_url }} \
+ -Delastic.apm.application_packages=com.openecs.assets"
+fi
+
+# Start the JAVA project
+
+RUN_DIR="$(dirname $0)/.."
+
+cd $RUN_DIR
+JAR_PATH="$(find ${RUN_DIR} -name 'assets-manager-[0-9]*.[0-9]*.[0-9]*.jar')"
+[ -z "$JAR_PATH" ] && echo "ABORTED: JAR program not found!" && exit 1
+
+$JAVA_HOME/bin/java $JAVA_OPTS $JAVA_APM -jar $JAR_PATH
+
